[[constraint]]
  name = "k8s.io/api"
  version = "kubernetes-1.10.0"

[[constraint]]
  name = "k8s.io/metrics"
  version = "kubernetes-1.10.0"

[[constraint]]
  name = "k8s.io/apimachinery"
  version = "kubernetes-1.10.0"

[[constraint]]
  name = "k8s.io/client-go"
  version = "7.0"

[[constraint]]
  name = "github.com/gdamore/tcell"
  version = "1.0"

[[constraint]]
  branch = "master"
  name = "github.com/rivo/tview"